In [32]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plot

from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix, mean_squared_error, roc_curve, roc_auc_score
from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.model_selection import train_test_split as tts, cross_val_score

In [12]:
import os
os.chdir("D:/GreyAtom/Datasets/09292018")

df = pd.read_csv("diabetes.csv")
df.head()

pregnancies  glucose  diastolic  triceps  insulin   bmi    dpf  age  \
0            6      148         72       35        0  33.6  0.627   50   
1            1       85         66       29        0  26.6  0.351   31   
2            8      183         64        0        0  23.3  0.672   32   
3            1       89         66       23       94  28.1  0.167   21   
4            0      137         40       35      168  43.1  2.288   33   

   diabetes  
0         1  
1         0  
2         1  
3         0  
4         1

In [13]:
X = df.drop(["diabetes"], axis = 1)
y = df["diabetes"]

In [14]:
X_train, X_test, y_train, y_test = tts(X, y, test_size = 0.3, random_state = 42)

In [15]:
knn = KNeighborsClassifier(n_neighbors=6)
knn_model = knn.fit(X_train, y_train)

In [16]:
y_pred = knn_model.predict(X_test)

In [19]:
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[124  27]
 [ 42  38]]
             precision    recall  f1-score   support

          0       0.75      0.82      0.78       151
          1       0.58      0.47      0.52        80

avg / total       0.69      0.70      0.69       231



In [42]:
y_pred_proba = knn.predict_proba(X_test)[:,1]
print(y_pred_proba[3], y_pred[3])

fpr, tpr, thresholds = roc_curve(y_test, y_pred_proba)
roc_auc_score(y_test, y_pred_proba)

0.3333333333333333 0


0.7300496688741722

In [20]:
Logistic = LogisticRegression()
Logistic.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [21]:
ylog_pred = Logistic.predict(X_test)

In [24]:
ylog_pred[:10]

array([0, 0, 0, 0, 0, 0, 0, 1, 1, 1], dtype=int64)

In [25]:
list(y_test[:10])

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [38]:
print(confusion_matrix(y_test, ylog_pred))
print(classification_report(y_test, ylog_pred))

ylog_pred_proba = Logistic.predict_proba(X_test)[:,1]
print(ylog_pred_proba[3], ylog_pred[3])

[[126  25]
 [ 32  48]]
             precision    recall  f1-score   support

          0       0.80      0.83      0.82       151
          1       0.66      0.60      0.63        80

avg / total       0.75      0.75      0.75       231

0.21973245026302712 0


In [39]:
fpr, tpr, thresholds = roc_curve(y_test, ylog_pred_proba)
roc_auc_score(y_test, ylog_pred_proba)

0.805794701986755