In [4]:
import os
import numpy as np
import pandas as pd
os.chdir ('D:\GreyAtom\Datasets')

In [9]:
taxis_data_np = np.genfromtxt("nyc_taxis.csv", delimiter=',', skip_header=1)
taxi_data_pd = pd.read_csv("nyc_taxis.csv")

In [10]:
taxi_ten_np = taxis_data_np[:10]

In [11]:
taxi_ten_np

array([[2.0160e+03, 1.0000e+00, 1.0000e+00, 5.0000e+00, 0.0000e+00,
        2.0000e+00, 4.0000e+00, 2.1000e+01, 2.0370e+03, 5.2000e+01,
        8.0000e-01, 5.5400e+00, 1.1650e+01, 6.9990e+01, 1.0000e+00],
       [2.0160e+03, 1.0000e+00, 1.0000e+00, 5.0000e+00, 0.0000e+00,
        2.0000e+00, 1.0000e+00, 1.6290e+01, 1.5200e+03, 4.5000e+01,
        1.3000e+00, 0.0000e+00, 8.0000e+00, 5.4300e+01, 1.0000e+00],
       [2.0160e+03, 1.0000e+00, 1.0000e+00, 5.0000e+00, 0.0000e+00,
        2.0000e+00, 6.0000e+00, 1.2700e+01, 1.4620e+03, 3.6500e+01,
        1.3000e+00, 0.0000e+00, 0.0000e+00, 3.7800e+01, 2.0000e+00],
       [2.0160e+03, 1.0000e+00, 1.0000e+00, 5.0000e+00, 0.0000e+00,
        2.0000e+00, 6.0000e+00, 8.7000e+00, 1.2100e+03, 2.6000e+01,
        1.3000e+00, 0.0000e+00, 5.4600e+00, 3.2760e+01, 1.0000e+00],
       [2.0160e+03, 1.0000e+00, 1.0000e+00, 5.0000e+00, 0.0000e+00,
        2.0000e+00, 6.0000e+00, 5.5600e+00, 7.5900e+02, 1.7500e+01,
        1.3000e+00, 0.0000e+00, 0.0000e+00, 

In [12]:
rows_391_to_500 = taxis_data_np[391:500]

In [14]:
rows_32_to_78_columns_5 = taxis_data_np[32:78,5]

In [15]:
trip_distance_miles = taxis_data_np[:,7]
trip_length_seconds = taxis_data_np[:,8]
trip_length_hours = trip_length_seconds/3600

In [16]:
trip_length_hours

array([0.56583333, 0.42222222, 0.40611111, ..., 0.78388889, 0.30083333,
       0.47527778])

In [17]:
trip_length_hours.max()

23.995277777777776

In [36]:
ones = np.array([[1,1,1], [1,1,1]])

In [37]:
zeros = np.array([0,0,0])
zeros = zeros.reshape(1,3)

In [38]:
concat = np.concatenate([ones, zeros], axis=0)
concat

array([[1, 1, 1],
       [1, 1, 1],
       [0, 0, 0]])

In [42]:
twos = np.array([2,2,2])

In [43]:
twos = twos.reshape(3,1)

In [45]:
concat_1 = np.concatenate([concat, twos], axis=1)
concat_1

array([[1, 1, 1, 2],
       [1, 1, 1, 2],
       [0, 0, 0, 2]])