In [11]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plot

from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix, mean_squared_error, roc_curve, roc_auc_score, accuracy_score
from sklearn.linear_model import LinearRegression, LogisticRegression, Ridge
from sklearn.model_selection import train_test_split as tts, cross_val_score
from sklearn.preprocessing import Imputer, scale, StandardScaler
from sklearn.pipeline import Pipeline

import os
os.chdir("D:/GreyAtom/Datasets/09292018")

df = pd.read_csv("white-wine.csv")
df.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.0              0.27         0.36            20.7      0.045   
1            6.3              0.30         0.34             1.6      0.049   
2            8.1              0.28         0.40             6.9      0.050   
3            7.2              0.23         0.32             8.5      0.058   
4            7.2              0.23         0.32             8.5      0.058   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 45.0                 170.0   1.0010  3.00       0.45   
1                 14.0                 132.0   0.9940  3.30       0.49   
2                 30.0                  97.0   0.9951  3.26       0.44   
3                 47.0                 186.0   0.9956  3.19       0.40   
4                 47.0                 186.0   0.9956  3.19       0.40   

   alcohol  quality  
0      8.8        6  
1      9.5        6  
2     10.1        6  
3      9.9        6  
4      9.9        6

In [12]:
X = df.drop(["quality"], axis = 1)
y = df["quality"]

In [13]:
X_scaled = scale(X)
X_scaled[1]

array([-0.65750113,  0.21589563,  0.04800112, -0.94476527,  0.14774708,
       -1.25301866, -0.14968462, -0.00915417,  0.74002864,  0.00134185,
       -0.82427568])

In [14]:
steps = [('scaler', StandardScaler()), ('knn', KNeighborsClassifier(n_neighbors=6))]

In [15]:
pipeline = Pipeline(steps)

In [19]:
X_train, X_test, y_train, y_test = tts(X, y, test_size = 0.3, random_state = 42)
knn_scaled = pipeline.fit(X_train, y_train)

y_pred = knn_scaled.predict(X_test)

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[  1   0   5   1   0   0]
 [  1   5  19  11   4   0]
 [  1  16 264 126  16   3]
 [  0   2 191 406  66   3]
 [  0   0  27 129 118   6]
 [  0   0   4  21  20   4]]
             precision    recall  f1-score   support

          3       0.33      0.14      0.20         7
          4       0.22      0.12      0.16        40
          5       0.52      0.62      0.56       426
          6       0.59      0.61      0.60       668
          7       0.53      0.42      0.47       280
          8       0.25      0.08      0.12        49

avg / total       0.53      0.54      0.53      1470



In [20]:
accuracy_score(y_test, y_pred)

0.5428571428571428