In [2]:
list_1 = []
for x in range(1,11):
    list_1.append(x)
list_1

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [10]:
list_2 = []
def sequence_a_num(x):
    return(x**2)

for x in list_1:
    list_2.append(sequence_a_num(x))

In [11]:
list_2

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [12]:
list_2 = map(sequence_a_num, list_1)

In [13]:
list(list_2)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [14]:
import os
os.chdir("D:\GreyAtom\Datasets")

In [15]:
os.getcwd()

'D:\\GreyAtom\\Datasets'

In [17]:
import pandas as pd
df = pd.read_csv("ipl_matches_small.csv")

In [19]:
df.head(2)

match_code        date         city                  team1           team2  \
0      392203  01-05-2009  East London  Kolkata Knight Riders  Mumbai Indians   
1      392203  01-05-2009  East London  Kolkata Knight Riders  Mumbai Indians   

      toss_winner toss_decision          winner win_type  win_margin  \
0  Mumbai Indians           bat  Mumbai Indians     runs           9   
1  Mumbai Indians           bat  Mumbai Indians     runs           9   

        ...              batsman   non_striker    bowler runs extras total  \
0       ...        ST Jayasuriya  SR Tendulkar  I Sharma    0      1     1   
1       ...        ST Jayasuriya  SR Tendulkar  I Sharma    1      0     1   

   extras_type  player_out  wicket_kind wicket_fielders  
0        wides         NaN          NaN             NaN  
1          NaN         NaN          NaN             NaN  

[2 rows x 23 columns]

In [24]:
list_1 = [1,2,3,4,5]
list_2 = [6,7,8,9,10]
list_3 = []

for x, y in zip(list_1, list_2):
    list_3.append(x+y)

In [25]:
print (list_3)

[7, 9, 11, 13, 15]


In [33]:
import math as m
def log10(number):
    return m.log10(number)

In [40]:
import math
list_1 = [2,5,3,8,5,9]
results = []
for x in list_1:
    results.append(math.log10(x))
print(results)

[0.3010299956639812, 0.6989700043360189, 0.47712125471966244, 0.9030899869919435, 0.6989700043360189, 0.9542425094393249]


In [41]:
import math
list_1 = [2,5,3,8,5,9]
results = list(map(lambda x: math.log10(x), list_1))

In [39]:
print(results)

[0.3010299956639812, 0.6989700043360189, 0.47712125471966244, 0.9030899869919435, 0.6989700043360189, 0.9542425094393249]


In [44]:
print (sorted(results, reverse=True))

[0.9542425094393249, 0.9030899869919435, 0.6989700043360189, 0.6989700043360189, 0.47712125471966244, 0.3010299956639812]


In [45]:
def li(*args):
    for x in args:
        print (x)

li(3,6,5,6,9)

3
6
5
6
9


In [48]:
def multiply(*args):
    z = 2
    for x in args:
        print (z*x)

multiply(3,6,5,6,9)

6
12
10
12
18


In [49]:
list_1 = [[1,2,3], [4,5,6], [7,8,9]]
import numpy as np
list_beautified = np.array(list_1)

In [52]:
list_beautified

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [51]:
list_beautified.shape

(3, 3)

In [53]:
print(type(list_beautified))

<class 'numpy.ndarray'>


In [56]:
print(list_beautified[1,2])

6


In [57]:
#Generating an identity matrix of say size 5
our_identity_matrix = np.eye(5)
our_identity_matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [58]:
os.chdir("D:\GreyAtom\Datasets")

In [59]:
os.getDir()

AttributeError: module 'os' has no attribute 'getDir'

In [60]:
os.getcwd()

'D:\\GreyAtom\\Datasets'

In [61]:
ls

 Volume in drive D is DATA
 Volume Serial Number is 347B-C42C

 Directory of D:\GreyAtom\Datasets

14-07-2018  15:30    <DIR>          .
14-07-2018  15:30    <DIR>          ..
14-07-2018  09:38    <DIR>          game-of-thrones
14-07-2018  10:47           257,011 ipl_matches_small.csv
14-07-2018  15:30           385,172 weather_small_2012.csv
               2 File(s)        642,183 bytes
               3 Dir(s)  500,055,228,416 bytes free


In [66]:
import numpy as npn
weather = np.genfromtxt("weather_small_2012.csv", delimiter=",")

In [67]:
weather

array([[   nan,    nan,    nan, ...,    nan,    nan,    nan],
       [   nan,  -1.8 ,  -3.9 , ...,   4.  ,   8.  , 101.24],
       [   nan,  -1.8 ,  -3.7 , ...,   4.  ,   8.  , 101.24],
       ...,
       [   nan,  -0.5 ,  -1.5 , ...,  28.  ,   4.8 ,  99.95],
       [   nan,  -0.2 ,  -1.8 , ...,  28.  ,   9.7 ,  99.91],
       [   nan,   0.  ,  -2.1 , ...,  30.  ,  11.3 ,  99.89]])

In [68]:
print(weather[1])

[   nan  -1.8   -3.9   86.     4.     8.   101.24]


In [84]:
temperature = (weather[1:,1])
print(type(temperature[1]))

<class 'numpy.float64'>


In [90]:
def CelsiustoFahrenheit(celsius):
    Fahrenheit = []
    for x in celsius:
        Fahrenheit.append((x*9/5)+32)
    print(Fahrenheit)
    
CelsiustoFahrenheit(temperature)

[28.76, 28.76, 28.76, 29.3, 29.3, 29.48, 29.3, 29.48, 29.48, 29.66, 30.2, 31.1, 31.64, 32.36, 33.44, 35.24, 36.68, 37.4, 38.839999999999996, 37.58, 37.76, 39.2, 39.92, 41.54, 41.36, 40.28, 39.02, 38.660000000000004, 37.22, 36.68, 36.14, 35.6, 35.42, 35.24, 34.7, 35.96, 35.06, 33.98, 33.98, 32.0, 30.74, 28.22, 24.62, 23.36, 21.92, 21.560000000000002, 19.4, 18.68, 15.8, 14.54, 13.100000000000001, 11.66, 9.32, 8.779999999999998, 8.059999999999999, 6.800000000000001, 5.359999999999996, 5.0, 4.459999999999997, 5.18, 5.18, 4.82, 5.18, 5.359999999999996, 4.459999999999997, 3.559999999999995, 2.6599999999999966, 1.5800000000000018, 0.8599999999999959, 1.3999999999999986, 1.2199999999999989, 0.8599999999999959, 0.5, -0.21999999999999886, -0.5799999999999983, -1.2999999999999972, -1.2999999999999972, -1.480000000000004, -1.2999999999999972, -0.759999999999998, -0.04000000000000625, 1.759999999999998, 4.640000000000004, 6.440000000000001, 7.34, 9.68, 11.66, 13.64, 15.079999999999998, 15.979999999

In [91]:
print(Fahrenheit)

None


In [92]:
temperature = (weather[1:,1])
farenheit = (temperature*9/5)+32
farenheit

array([28.76, 28.76, 28.76, ..., 31.1 , 31.64, 32.  ])

In [97]:
farenheit_above_30 = farenheit>30
print(farenheit_above_30)
wind_speed = (weather[1:,4])
print(len(wind_speed[farenheit_above_30]))
print(wind_speed[farenheit_above_30])

[False False False ...  True  True  True]
6838
[ 9.  7.  9. ... 28. 28. 30.]


In [102]:
print("Max", temperature.max())
print("Min", temperature.min())
print("Mean Temp", temperature.mean())
print("Argmax", temperature.argmax())
print("Argmin", temperature.argmin())

Max 33.0
Min -23.3
Mean Temp 8.798144353369764
Argmax 4143
Argmin 344


In [108]:
arr = np.random.randint(100, size=9).reshape(3,3)

In [109]:
arr

array([[29, 89, 44],
       [48, 41, 95],
       [38, 15, 25]])

In [110]:
import pandas as pd
df = pd.read_csv("ipl_matches_small.csv", header=None)

In [116]:
df.head()

0           1            2                      3               4   \
0  match_code        date         city                  team1           team2   
1      392203  01-05-2009  East London  Kolkata Knight Riders  Mumbai Indians   
2      392203  01-05-2009  East London  Kolkata Knight Riders  Mumbai Indians   
3      392203  01-05-2009  East London  Kolkata Knight Riders  Mumbai Indians   
4      392203  01-05-2009  East London  Kolkata Knight Riders  Mumbai Indians   

               5              6               7         8           9   \
0     toss_winner  toss_decision          winner  win_type  win_margin   
1  Mumbai Indians            bat  Mumbai Indians      runs           9   
2  Mumbai Indians            bat  Mumbai Indians      runs           9   
3  Mumbai Indians            bat  Mumbai Indians      runs           9   
4  Mumbai Indians            bat  Mumbai Indians      runs           9   

        ...                    13             14        15    16      17  \
0       ...               batsman    non_striker    bowler  runs  extras   
1       ...         ST Jayasuriya   SR Tendulkar  I Sharma     0       1   
2       ...         ST Jayasuriya   SR Tendulkar  I Sharma     1       0   
3       ...          SR Tendulkar  ST Jayasuriya  I Sharma     0       1   
4       ...          SR Tendulkar  ST Jayasuriya  I Sharma     0       0   

      18           19          20           21               22  
0  total  extras_type  player_out  wicket_kind  wicket_fielders  
1      1        wides         NaN          NaN              NaN  
2      1          NaN         NaN          NaN              NaN  
3      1        wides         NaN          NaN              NaN  
4      0          NaN         NaN          NaN              NaN  

[5 rows x 23 columns]

In [118]:
df.iloc[:,2]

0              city
1       East London
2       East London
3       East London
4       East London
5       East London
6       East London
7       East London
8       East London
9       East London
10      East London
11      East London
12      East London
13      East London
14      East London
15      East London
16      East London
17      East London
18      East London
19      East London
20      East London
21      East London
22      East London
23      East London
24      East London
25      East London
26      East London
27      East London
28      East London
29      East London
           ...     
1422         Jaipur
1423         Jaipur
1424         Jaipur
1425         Jaipur
1426         Jaipur
1427         Jaipur
1428         Jaipur
1429         Jaipur
1430         Jaipur
1431         Jaipur
1432         Jaipur
1433         Jaipur
1434         Jaipur
1435         Jaipur
1436         Jaipur
1437         Jaipur
1438         Jaipur
1439         Jaipur
1440         Jaipur


In [120]:
df.loc["city"]

KeyError: 'the label [city] is not in the [index]'